version: '3.4'

services:
  basket:
    build:
      context: .
      dockerfile: basket/Dockerfile
      target: dev
    volumes:
      - './basket/src:/app'
    environment:
      CACHE_HOST: basket-cache
      CACHE_PORT: 6379
  basket-cache:
    image: redis:alpine
  catalog:
    build:
      context: .
      dockerfile: catalog/Dockerfile
      target: dev
    volumes:
      - './catalog/src:/app'
    environment:
      DB_URL: mongodb://catalog-db:27017/catalog
#    env_file:
#      - <PATH_TO_FILE>
  catalog-db:
    image: mongo
    volumes:
      - '/data/db'
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: dev
    ports:
      - '8080:80'
    volumes:
      - './gateway/src:/app'

# docker compose sets up network automatically
