version: '3.4'
services:
  basket:
    restart: always
    build:
      context: .
      dockerfile: basket/Dockerfile
      target: dev
    environment:
      CACHE_HOST: basket-cache
      CACHE_PORT: 6379
    volumes:
      - './basket/src:/app'
  basket-cache:
    image: redis:alpine
  catalog:
    restart: always
    build:
      context: .
      dockerfile: catalog/Dockerfile
      target: dev
    volumes:
      - './catalog/src:/app'
    links:
      - catalog-db
    environment:
      DB_URL: mongodb://catalog-db:27017/catalog
  catalog-db:
    image: mongo
    volumes:
      - ./catalog/db:/data/db
  gateway:
    restart: always
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: dev
    ports:
      - '8080:80'
    volumes:
      - './gateway/src:/app'
